Feature: Add react-navigation support
dsznajder/create-react-native-project pull request #398
Opened 2021-06-26 15:13 UTC by Drakeoon

### Tasks:
- [x] Add node task for development
- [x] Add option to select `react-navigation` when initializing new project
- [x] Add setup & development notes in README.md
- [x] Fix husky error when initializing new project by running `git init` in new folder
- [ ] Add ability to choose react-navigation variant during new project initialization
- [ ] Implement Bottom Tab navigation setup
- [ ] Improve component reexports - `import Navigation from '~/navigation/index'` vs `import Navigation from '~/navigation'`

Side note: @dsznajder you may experience the issue with white background flickering when changing routes, but if you configure your device's theme under Developer Settings to use Dark Mode, it will get fixed. I think we shouldn't use black background when user has Light Mode enabled, what do you think?

### Preview:

2021-06-26 15:22 UTC, dsznajder commented
@Drakeoon True. We can change it to white as default, and in future, add light/dark mode support and integration.

2021-06-26 15:34 UTC, dsznajder requested changes

2021-06-26 15:34 UTC, dsznajder commented on package.json
> +    "build": "./bin/create-react-native-project",
This should probably run `yarn prepare` before.

2021-06-26 15:34 UTC, dsznajder commented on src/packages.ts
> +  }
Shouldn't be placed together with react-navigation as `module`?

2021-06-26 15:34 UTC, dsznajder commented on templates/common/App.tsx
> +import { StatusBar, StyleSheet } from 'react-native';
Modules should be placed on top of file, before relative imports

2021-06-26 15:34 UTC, dsznajder commented on templates/common/ios/Podfile
> -source 'https://github.com/CocoaPods/Specs.git'
😅

2021-06-26 15:34 UTC, dsznajder commented on templates/common/ios/{%- project.name %}/AppDelegate.m
> +      rootView.backgroundColor = [UIColor blackColor];
Revert it and change backgroundColor to white :)
```suggestion
      rootView.backgroundColor = [UIColor whiteColor];
```

2021-06-26 15:34 UTC, dsznajder commented on templates/common/scripts/postinstall.sh
> +git init;
What do you think, after the whole process - to create the first commit?

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/navigation/index.tsx
> +};
Note for future me. Add TS helpers for screen types.

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/screens/Home/Home.tsx
> +});
Normally styles are placed at the end of the file, so please move them. The only reason why navigator had those, was that - I've been preparing it for future theming :)

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/screens/Home/Home.tsx
> +      <Typography>{`DummyProject - Home Page`}</Typography>
Use text from internationalization.
```suggestion
      <Typography>{t('screens.homeScreen.title')}</Typography>
```

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/screens/Home/Home.tsx
> +  const { navigation } = props;
```suggestion
const HomeScreen = ({ navigation }: Props) => {
```

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/screens/Home/Home.tsx
> +  const { navigation } = props;
And at the end of file: `export default HomeScreen;`

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/screens/Home/index.tsx
> +export { default } from './Home';
Move whole `Home.tsx` there.

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/screens/Settings/index.tsx
> +export { default } from './Settings';
Same as with `Home.tsx`. Move the whole `Settings.tsx` file there.

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/screens/Settings/Settings.tsx
> +  const { navigation } = props;
👀

2021-06-26 15:34 UTC, dsznajder commented on templates/navigation/src/screens/Settings/Settings.tsx
> +      <Typography>{`Settings Screen`}</Typography>
🗒️

2021-06-26 21:51 UTC, Drakeoon commented on package.json
> +    "build": "./bin/create-react-native-project",
I agree 👍🏻  This leaves the `dev` task a little obsolete, so I decided to remove it

2021-06-26 21:56 UTC, Drakeoon commented on src/packages.ts
> +  }
I initially thought the same, but then I would need to add `modules.navigation` to `if` `ejs` statements in the code. I've decided that `gestureHandler` has it's own responsibility and I don't want to flood it with another module. See example below of a scenario that would happen everywhere:
```
// Before
<% if (modules.gestureHandler) { %>
  
// After
 <% if (modules.gestureHandler || modules.navigation) { %>
 ```

I think this way we don't need to modify conditional statements everywhere, we can just rely on `gestureHandler` doing it's thing, as it is only responsible for making gesture handler work properly

2021-06-26 21:57 UTC, Drakeoon commented on templates/common/ios/Podfile
> -source 'https://github.com/CocoaPods/Specs.git'
Is this change okay? I think we decided to remove it after our discussions 😄

2021-06-26 21:59 UTC, Drakeoon commented on templates/common/ios/{%- project.name %}/AppDelegate.m
> +      rootView.backgroundColor = [UIColor blackColor];
Understood 😄  Is there any reason behind that? For devices below iOS 13 we will always have this weird flicker thing with white background

2021-06-26 22:12 UTC, Drakeoon commented on templates/common/scripts/postinstall.sh
> +git init;
Sounds awesome, I'll add that as this seems to be a quick change

2021-06-26 22:27 UTC, Drakeoon commented on templates/common/ios/{%- project.name %}/AppDelegate.m
> +      rootView.backgroundColor = [UIColor blackColor];
Oh, saw your comment above the whole code review notes, now I see 👍🏻

2021-06-27 06:00 UTC, dsznajder commented on templates/common/ios/Podfile
> -source 'https://github.com/CocoaPods/Specs.git'
Yes, just noting that it caused issues :)

2021-06-27 06:02 UTC, dsznajder commented on package.json
> +    "build": "./bin/create-react-native-project",
Yeah, that's even better :)

2021-06-27 14:47 UTC, dsznajder reviewed
Waiting for rest 👀

2021-06-28 07:18 UTC, dsznajder approved these changes

2021-07-01 18:32 UTC, dsznajder requested changes
Last polishes and should be ready 👀

2021-07-01 18:32 UTC, dsznajder commented on src/packages.ts
> +            main: ['@react-navigation/native-stack'],
```suggestion
            main: ['react-native-screens'],
```

2021-07-01 18:32 UTC, dsznajder commented on templates/navigation/src/navigation/index.tsx
> +import { createNativeStackNavigator } from '@react-navigation/native-stack';
```suggestion
import { createNativeStackNavigator } from 'react-native-screens/native-stack';
```

2021-07-01 18:32 UTC, dsznajder commented on src/index.ts
> +    options.modules.gestureHandler = true;
+ `react-native-screens` when `nativeStack` is chosen

```suggestion
    options.modules.gestureHandler = true;
    options.modules.reanimated = true;
```

2021-07-01 18:32 UTC, dsznajder commented on templates/navigation/src/screens/Home/index.tsx
> +    justifyContent: 'center',
```suggestion
```

2021-07-01 18:32 UTC, dsznajder commented on templates/navigation/src/screens/Home/index.tsx
> +    <Block style={styles.container}>
```suggestion
    <Block flex={1} alignCenter justifyCenter style={styles.container}>
```

2021-07-01 18:34 UTC, Drakeoon commented on src/packages.ts
> +            main: ['@react-navigation/native-stack'],
react-native-screens is always included when we have `navigation` chosen, no matter which variant:

```
navigation: {
      main: [
        '@react-native-community/masked-view',
        '@react-navigation/native',
        'react-native-screens',
        'react-native-safe-area-context',
      ],
    },
```

2021-07-01 19:11 UTC, dsznajder commented on src/packages.ts
> +            main: ['@react-navigation/native-stack'],
Okay, so it should be removed

2021-07-05 23:13 UTC, Drakeoon commented
@dsznajder I've applied the changes you requested - I also performed manual checks for Android device on each new navigation variant - seems to be all right 👍🏻 I'll check tomorrow on MacOS, but I think this is already in a good shape

2021-07-09 19:23 UTC, dsznajder approved these changes
Thanks!

2021-07-09 19:24 UTC, merged